apiVersion: app.uppound.io/v1alpha1
kind: XApp
metadata:
  name: example
spec:
  compositionSelector:
    matchLabels:
      language: kcl
  parameters:
    id: uppound-az
    containers:
      - name: frontend
        image: xpkg.upbound.io/upbound/uppound-demo-frontend:latest
      - name: backend
        image: xpkg.upbound.io/upbound/uppound-demo-backend:latest
    region: eastus
    version: "1.30"
    nodes:
      count: 3
      instanceType: Standard_D2s_v3
  writeConnectionSecretToRef:
    name: uppound-azure-kubeconfig
    namespace: default
